---
- name: Post installation
  hosts: all
  gather_facts: true
  become: true
  roles:
    - requirements

- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download

- hosts: master
  become: true
  roles:
    - role: k3s/master

- hosts: node
  become: true
  roles:
    - role: k3s/node

- hosts: master
  become: true
  roles:
    - role: k3s/post
