# Rhel Family upgrade
- name: Mettre à jour le cache des repositories
  dnf:
    update_cache: yes

- name: Mettre à jour tous les packages vers leur dernière version
  dnf:
    name: "*"
    state: latest

- name: Vérification à partir du fichier reboot_required
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required

- name: Lancement du reboot
  reboot:
    msg: "Reboot via ansible"
    connect_timeout: "{{ reboot_connect_timeout }}"
    reboot_timeout: "{{ reboot_timeout }}"
    pre_reboot_delay: "{{reboot_pre_reboot_delay}}"
    post_reboot_delay: "{{ reboot_post_reboot_delay }}"
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Installation prérequis géneraux rhel
  dnf:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: 
    - "{{ prerequis_generaux }}"
    - "{{ prerequis_rhel }}" 

- name: Update repositories cache
  dnf:
    update_cache: yes