---

- name: Copier le fichier de service K3s
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Activer et vérifier le service K3s
  systemd:
    name: k3s-node
    daemon_reload: true
    state: restarted
    enabled: true
